/*
Deployment script for ObservationDB_IMP

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ObservationDB_IMP"
:setvar DefaultFilePrefix "ObservationDB_IMP"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL13.SAEON\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL13.SAEON\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[SchemaColumn]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[SchemaColumn] (
    [ID]                   UNIQUEIDENTIFIER NOT NULL,
    [DataSchemaID]         UNIQUEIDENTIFIER NOT NULL,
    [Name]                 VARCHAR (100)    NOT NULL,
    [SchemaColumnTypeID]   UNIQUEIDENTIFIER NOT NULL,
    [Width]                INT              NULL,
    [Format]               VARCHAR (50)     NULL,
    [PhenomenonID]         UNIQUEIDENTIFIER NULL,
    [PhenomenonOfferingID] UNIQUEIDENTIFIER NULL,
    [PhenomenonUOMID]      UNIQUEIDENTIFIER NULL,
    [FixedTime]            VARCHAR (50)     NULL,
    [EmptyValue]           VARCHAR (50)     NULL,
    [UserId]               UNIQUEIDENTIFIER NOT NULL,
    [AddedAt]              DATETIME         NULL,
    [UpdatedAt]            DATETIME         NULL,
    CONSTRAINT [PK_SchemaColumn] PRIMARY KEY NONCLUSTERED ([ID] ASC),
    CONSTRAINT [UX_SchemaColumn] UNIQUE NONCLUSTERED ([DataSchemaID] ASC, [Name] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [dbo].[SchemaColumn].[CX_SchemaColumn]...';


GO
CREATE CLUSTERED INDEX [CX_SchemaColumn]
    ON [dbo].[SchemaColumn]([AddedAt] ASC);


GO
PRINT N'Creating [dbo].[SchemaColumn].[IX_SchemaColumn_DataSchemaID]...';


GO
CREATE NONCLUSTERED INDEX [IX_SchemaColumn_DataSchemaID]
    ON [dbo].[SchemaColumn]([DataSchemaID] ASC);


GO
PRINT N'Creating [dbo].[SchemaColumn].[IX_SchemaColumn_SchemaColumnTypeID]...';


GO
CREATE NONCLUSTERED INDEX [IX_SchemaColumn_SchemaColumnTypeID]
    ON [dbo].[SchemaColumn]([SchemaColumnTypeID] ASC);


GO
PRINT N'Creating [dbo].[SchemaColumn].[IX_SchemaColumn_PhenomenonID]...';


GO
CREATE NONCLUSTERED INDEX [IX_SchemaColumn_PhenomenonID]
    ON [dbo].[SchemaColumn]([PhenomenonID] ASC);


GO
PRINT N'Creating [dbo].[SchemaColumn].[IX_SchemaColumn_PhenomenonOfferingID]...';


GO
CREATE NONCLUSTERED INDEX [IX_SchemaColumn_PhenomenonOfferingID]
    ON [dbo].[SchemaColumn]([PhenomenonOfferingID] ASC);


GO
PRINT N'Creating [dbo].[SchemaColumn].[IX_SchemaColumn_PhenomenonUOMID]...';


GO
CREATE NONCLUSTERED INDEX [IX_SchemaColumn_PhenomenonUOMID]
    ON [dbo].[SchemaColumn]([PhenomenonUOMID] ASC);


GO
PRINT N'Creating [dbo].[SchemaColumn].[IX_SchemaColumn_UserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_SchemaColumn_UserId]
    ON [dbo].[SchemaColumn]([UserId] ASC);


GO
PRINT N'Creating [dbo].[SchemaColumnType]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[SchemaColumnType] (
    [ID]          UNIQUEIDENTIFIER NOT NULL,
    [Name]        VARCHAR (50)     NOT NULL,
    [Description] VARCHAR (250)    NOT NULL,
    [UserId]      UNIQUEIDENTIFIER NOT NULL,
    [AddedAt]     DATETIME         NULL,
    [UpdatedAt]   DATETIME         NULL,
    CONSTRAINT [PK_SchemaColumnType] PRIMARY KEY NONCLUSTERED ([ID] ASC),
    CONSTRAINT [UX_SchemaColumnType] UNIQUE NONCLUSTERED ([Name] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [dbo].[SchemaColumnType].[CX_SchemaColumnType]...';


GO
CREATE CLUSTERED INDEX [CX_SchemaColumnType]
    ON [dbo].[SchemaColumnType]([AddedAt] ASC);


GO
PRINT N'Creating [dbo].[SchemaColumnType].[IX_SchemaColumnType_UserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_SchemaColumnType_UserId]
    ON [dbo].[SchemaColumnType]([UserId] ASC);


GO
PRINT N'Creating [dbo].[DF_SchemaColumn_ID]...';


GO
ALTER TABLE [dbo].[SchemaColumn]
    ADD CONSTRAINT [DF_SchemaColumn_ID] DEFAULT newid() FOR [ID];


GO
PRINT N'Creating [dbo].[DF_SchemaColumn_AddedAt]...';


GO
ALTER TABLE [dbo].[SchemaColumn]
    ADD CONSTRAINT [DF_SchemaColumn_AddedAt] DEFAULT GetDate() FOR [AddedAt];


GO
PRINT N'Creating [dbo].[DF_SchemaColumn_UpdatedAt]...';


GO
ALTER TABLE [dbo].[SchemaColumn]
    ADD CONSTRAINT [DF_SchemaColumn_UpdatedAt] DEFAULT GetDate() FOR [UpdatedAt];


GO
PRINT N'Creating [dbo].[DF_SchemaColumnType_ID]...';


GO
ALTER TABLE [dbo].[SchemaColumnType]
    ADD CONSTRAINT [DF_SchemaColumnType_ID] DEFAULT newid() FOR [ID];


GO
PRINT N'Creating [dbo].[DF_SchemaColumnType_AddedAt]...';


GO
ALTER TABLE [dbo].[SchemaColumnType]
    ADD CONSTRAINT [DF_SchemaColumnType_AddedAt] DEFAULT GetDate() FOR [AddedAt];


GO
PRINT N'Creating [dbo].[DF_SchemaColumnType_UpdatedAt]...';


GO
ALTER TABLE [dbo].[SchemaColumnType]
    ADD CONSTRAINT [DF_SchemaColumnType_UpdatedAt] DEFAULT GetDate() FOR [UpdatedAt];


GO
PRINT N'Creating [dbo].[FK_SchemaColumn_DataSchema]...';


GO
ALTER TABLE [dbo].[SchemaColumn] WITH NOCHECK
    ADD CONSTRAINT [FK_SchemaColumn_DataSchema] FOREIGN KEY ([DataSchemaID]) REFERENCES [dbo].[DataSchema] ([ID]);


GO
PRINT N'Creating [dbo].[FK_SchemaColumn_SchemaColumnType]...';


GO
ALTER TABLE [dbo].[SchemaColumn] WITH NOCHECK
    ADD CONSTRAINT [FK_SchemaColumn_SchemaColumnType] FOREIGN KEY ([SchemaColumnTypeID]) REFERENCES [dbo].[SchemaColumnType] ([ID]);


GO
PRINT N'Creating [dbo].[FK_SchemaColumn_Phenomenon]...';


GO
ALTER TABLE [dbo].[SchemaColumn] WITH NOCHECK
    ADD CONSTRAINT [FK_SchemaColumn_Phenomenon] FOREIGN KEY ([PhenomenonID]) REFERENCES [dbo].[Phenomenon] ([ID]);


GO
PRINT N'Creating [dbo].[FK_SchemaColumn_PhenomenonOffering]...';


GO
ALTER TABLE [dbo].[SchemaColumn] WITH NOCHECK
    ADD CONSTRAINT [FK_SchemaColumn_PhenomenonOffering] FOREIGN KEY ([PhenomenonOfferingID]) REFERENCES [dbo].[PhenomenonOffering] ([ID]);


GO
PRINT N'Creating [dbo].[FK_SchemaColumn_PhenomenonUOM]...';


GO
ALTER TABLE [dbo].[SchemaColumn] WITH NOCHECK
    ADD CONSTRAINT [FK_SchemaColumn_PhenomenonUOM] FOREIGN KEY ([PhenomenonUOMID]) REFERENCES [dbo].[PhenomenonUOM] ([ID]);


GO
PRINT N'Creating [dbo].[FK_SchemaColumn_aspnet_Users]...';


GO
ALTER TABLE [dbo].[SchemaColumn] WITH NOCHECK
    ADD CONSTRAINT [FK_SchemaColumn_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_SchemaColumnType_aspnet_Users]...';


GO
ALTER TABLE [dbo].[SchemaColumnType] WITH NOCHECK
    ADD CONSTRAINT [FK_SchemaColumnType_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[TR_SchemaColumn_Insert]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TRIGGER [dbo].[TR_SchemaColumn_Insert] ON [dbo].[SchemaColumn]
FOR INSERT
AS
BEGIN
    SET NoCount ON
    Update
        src
    set
        AddedAt = GETDATE(),
        UpdatedAt = NULL
    from
        inserted ins
        inner join SchemaColumn src
            on (ins.ID = src.ID)
END
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [dbo].[TR_SchemaColumn_Update]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TRIGGER [dbo].[TR_SchemaColumn_Update] ON [dbo].[SchemaColumn]
FOR UPDATE
AS
BEGIN
    SET NoCount ON
    --if UPDATE(AddedAt) RAISERROR ('Cannot update AddedAt.', 16, 1)
    Update
        src
    set
        UpdatedAt = GETDATE()
    from
        inserted ins
        inner join SchemaColumn src
            on (ins.ID = src.ID)
END
--< Added 2.0.11 20160908 TimPN
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [dbo].[TR_SchemaColumnType_Insert]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TRIGGER [dbo].[TR_SchemaColumnType_Insert] ON [dbo].[SchemaColumnType]
FOR INSERT
AS
BEGIN
    SET NoCount ON
    Update
        src
    set
        AddedAt = GETDATE(),
        UpdatedAt = NULL
    from
        inserted ins
        inner join SchemaColumnType src
            on (ins.ID = src.ID)
END
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [dbo].[TR_SchemaColumnType_Update]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TRIGGER [dbo].[TR_SchemaColumnType_Update] ON [dbo].[SchemaColumnType]
FOR UPDATE
AS
BEGIN
    SET NoCount ON
    --if UPDATE(AddedAt) RAISERROR ('Cannot update AddedAt.', 16, 1)
    Update
        src
    set
        UpdatedAt = GETDATE()
    from
        inserted ins
        inner join SchemaColumnType src
            on (ins.ID = src.ID)
END
--< Added 2.0.11 20160908 TimPN
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[SchemaColumn] WITH CHECK CHECK CONSTRAINT [FK_SchemaColumn_DataSchema];

ALTER TABLE [dbo].[SchemaColumn] WITH CHECK CHECK CONSTRAINT [FK_SchemaColumn_SchemaColumnType];

ALTER TABLE [dbo].[SchemaColumn] WITH CHECK CHECK CONSTRAINT [FK_SchemaColumn_Phenomenon];

ALTER TABLE [dbo].[SchemaColumn] WITH CHECK CHECK CONSTRAINT [FK_SchemaColumn_PhenomenonOffering];

ALTER TABLE [dbo].[SchemaColumn] WITH CHECK CHECK CONSTRAINT [FK_SchemaColumn_PhenomenonUOM];

ALTER TABLE [dbo].[SchemaColumn] WITH CHECK CHECK CONSTRAINT [FK_SchemaColumn_aspnet_Users];

ALTER TABLE [dbo].[SchemaColumnType] WITH CHECK CHECK CONSTRAINT [FK_SchemaColumnType_aspnet_Users];


GO
PRINT N'Update complete.';


GO
