/*
Deployment script for ObservationsTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ObservationsTest"
:setvar DefaultFilePrefix "ObservationsTest"
:setvar DefaultDataPath "D:\Program Files\Microsoft SQL Server\MSSQL14.SAEON\MSSQL\DATA\"
:setvar DefaultLogPath "D:\Program Files\Microsoft SQL Server\MSSQL14.SAEON\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


--GO
--IF EXISTS (SELECT 1
--           FROM   [master].[dbo].[sysdatabases]
--           WHERE  [name] = N'$(DatabaseName)')
--    BEGIN
--        ALTER DATABASE [$(DatabaseName)]
--            SET TEMPORAL_HISTORY_RETENTION ON 
--            WITH ROLLBACK IMMEDIATE;
--    END


GO
PRINT N'Dropping [dbo].[Observation].[IX_Observation_ValueDecade]...';


GO
DROP INDEX [IX_Observation_ValueDecade]
    ON [dbo].[Observation];


GO
PRINT N'Dropping [dbo].[Observation].[IX_Observation_ValueYear]...';


GO
DROP INDEX [IX_Observation_ValueYear]
    ON [dbo].[Observation];


GO
PRINT N'Dropping [dbo].[DF_DataSourceTransformation_ID]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [DF_DataSourceTransformation_ID];


GO
PRINT N'Dropping [dbo].[DF_DataSourceTransformation_Rank]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [DF_DataSourceTransformation_Rank];


GO
PRINT N'Dropping [dbo].[DF_DataSourceTransformation_AddedAt]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [DF_DataSourceTransformation_AddedAt];


GO
PRINT N'Dropping [dbo].[DF_DataSourceTransformation_UpdatedAt]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [DF_DataSourceTransformation_UpdatedAt];


GO
PRINT N'Dropping [dbo].[DF_ImportBatch_ID]...';


GO
ALTER TABLE [dbo].[ImportBatch] DROP CONSTRAINT [DF_ImportBatch_ID];


GO
PRINT N'Dropping [dbo].[DF_ImportBatch_ImportDate]...';


GO
ALTER TABLE [dbo].[ImportBatch] DROP CONSTRAINT [DF_ImportBatch_ImportDate];


GO
PRINT N'Dropping [dbo].[DF_ImportBatch_AddedAt]...';


GO
ALTER TABLE [dbo].[ImportBatch] DROP CONSTRAINT [DF_ImportBatch_AddedAt];


GO
PRINT N'Dropping [dbo].[DF_ImportBatch_UpdatedAt]...';


GO
ALTER TABLE [dbo].[ImportBatch] DROP CONSTRAINT [DF_ImportBatch_UpdatedAt];


GO
PRINT N'Dropping [dbo].[DF_ImportBatchSummary_ID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] DROP CONSTRAINT [DF_ImportBatchSummary_ID];


GO
PRINT N'Dropping [dbo].[DF_UserDownloads_UpdatedAt]...';


GO
ALTER TABLE [dbo].[UserDownloads] DROP CONSTRAINT [DF_UserDownloads_UpdatedAt];


GO
PRINT N'Dropping [dbo].[DF_UserDownloads_AddedAt]...';


GO
ALTER TABLE [dbo].[UserDownloads] DROP CONSTRAINT [DF_UserDownloads_AddedAt];


GO
PRINT N'Dropping [dbo].[DF_UserDownloads_ID]...';


GO
ALTER TABLE [dbo].[UserDownloads] DROP CONSTRAINT [DF_UserDownloads_ID];


GO
PRINT N'Dropping [dbo].[FK_DataLog_DataSourceTransformation]...';


GO
ALTER TABLE [dbo].[DataLog] DROP CONSTRAINT [FK_DataLog_DataSourceTransformation];


GO
PRINT N'Dropping [dbo].[FK_DataSourceTransformation_TransformationType]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [FK_DataSourceTransformation_TransformationType];


GO
PRINT N'Dropping [dbo].[FK_DataSourceTransformation_Sensor]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [FK_DataSourceTransformation_Sensor];


GO
PRINT N'Dropping [dbo].[FK_DataSourceTransformation_NewPhenomenon]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [FK_DataSourceTransformation_NewPhenomenon];


GO
PRINT N'Dropping [dbo].[FK_DataSourceTransformation_DataSource]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [FK_DataSourceTransformation_DataSource];


GO
PRINT N'Dropping [dbo].[FK_DataSourceTransformation_Phenomenon]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [FK_DataSourceTransformation_Phenomenon];


GO
PRINT N'Dropping [dbo].[FK_DataSourceTransformation_PhenomenonOffering]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [FK_DataSourceTransformation_PhenomenonOffering];


GO
PRINT N'Dropping [dbo].[FK_DataSourceTransformation_NewPhenomenonOffering]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [FK_DataSourceTransformation_NewPhenomenonOffering];


GO
PRINT N'Dropping [dbo].[FK_DataSourceTransformation_PhenomenonUOM]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [FK_DataSourceTransformation_PhenomenonUOM];


GO
PRINT N'Dropping [dbo].[FK_DataSourceTransformation_NewPhenomenonUOM]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] DROP CONSTRAINT [FK_DataSourceTransformation_NewPhenomenonUOM];


GO
PRINT N'Dropping [dbo].[FK_DataLog_ImportBatch]...';


GO
ALTER TABLE [dbo].[DataLog] DROP CONSTRAINT [FK_DataLog_ImportBatch];


GO
PRINT N'Dropping [dbo].[FK_ImportBatchSummary_ImportBatchID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] DROP CONSTRAINT [FK_ImportBatchSummary_ImportBatchID];


GO
PRINT N'Dropping [dbo].[FK_ImportBatch_DataSource]...';


GO
ALTER TABLE [dbo].[ImportBatch] DROP CONSTRAINT [FK_ImportBatch_DataSource];


GO
PRINT N'Dropping [dbo].[FK_ImportBatch_Status]...';


GO
ALTER TABLE [dbo].[ImportBatch] DROP CONSTRAINT [FK_ImportBatch_Status];


GO
PRINT N'Dropping [dbo].[FK_ImportBatch_StatusReason]...';


GO
ALTER TABLE [dbo].[ImportBatch] DROP CONSTRAINT [FK_ImportBatch_StatusReason];


GO
PRINT N'Dropping [dbo].[FK_Observation_ImportBatch]...';


GO
ALTER TABLE [dbo].[Observation] DROP CONSTRAINT [FK_Observation_ImportBatch];


GO
PRINT N'Dropping [dbo].[FK_ImportBatchSummary_SensorID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] DROP CONSTRAINT [FK_ImportBatchSummary_SensorID];


GO
PRINT N'Dropping [dbo].[FK_ImportBatchSummary_PhenomenonOfferingID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] DROP CONSTRAINT [FK_ImportBatchSummary_PhenomenonOfferingID];


GO
PRINT N'Dropping [dbo].[FK_ImportBatchSummary_PhenomenonUOMID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] DROP CONSTRAINT [FK_ImportBatchSummary_PhenomenonUOMID];


GO
PRINT N'Dropping [dbo].[FK_ImportBatchSummary_InstrumentID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] DROP CONSTRAINT [FK_ImportBatchSummary_InstrumentID];


GO
PRINT N'Dropping [dbo].[FK_ImportBatchSummary_StationID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] DROP CONSTRAINT [FK_ImportBatchSummary_StationID];


GO
PRINT N'Dropping [dbo].[FK_ImportBatchSummary_SiteID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] DROP CONSTRAINT [FK_ImportBatchSummary_SiteID];


GO
PRINT N'Dropping [dbo].[FK_UserDownloads_DigitalObjectIdentifiers]...';


GO
ALTER TABLE [dbo].[UserDownloads] DROP CONSTRAINT [FK_UserDownloads_DigitalObjectIdentifiers];


GO
PRINT N'Starting rebuilding table [dbo].[aspnet_PersonalizationAllUsers]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_aspnet_PersonalizationAllUsers] (
    [PathId]          UNIQUEIDENTIFIER NOT NULL,
    [PageSettings]    IMAGE            NOT NULL,
    [Test]            INT              NULL,
    [LastUpdatedDate] DATETIME         NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_aspnet_PersonalizationAllUsers1] PRIMARY KEY CLUSTERED ([PathId] ASC) ON [PRIMARY]
) ON [PRIMARY];

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[aspnet_PersonalizationAllUsers])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_aspnet_PersonalizationAllUsers] ([PathId], [PageSettings], [LastUpdatedDate])
        SELECT   [PathId],
                 [PageSettings],
                 [LastUpdatedDate]
        FROM     [dbo].[aspnet_PersonalizationAllUsers]
        ORDER BY [PathId] ASC;
    END

DROP TABLE [dbo].[aspnet_PersonalizationAllUsers];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_aspnet_PersonalizationAllUsers]', N'aspnet_PersonalizationAllUsers';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_aspnet_PersonalizationAllUsers1]', N'PK_aspnet_PersonalizationAllUsers', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
EXECUTE sp_tableoption @TableNamePattern = N'[dbo].[aspnet_PersonalizationAllUsers]', @OptionName = N'text in row', @OptionValue = N'6000';


GO
PRINT N'Starting rebuilding table [dbo].[aspnet_Profile]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_aspnet_Profile] (
    [UserId]               UNIQUEIDENTIFIER NOT NULL,
    [PropertyNames]        NTEXT            NOT NULL,
    [PropertyValuesString] NTEXT            NOT NULL,
    [PropertyValuesBinary] IMAGE            NOT NULL,
    [Test]                 INT              NULL,
    [LastUpdatedDate]      DATETIME         NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_aspnet_Profile1] PRIMARY KEY CLUSTERED ([UserId] ASC) ON [PRIMARY]
) ON [PRIMARY];

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[aspnet_Profile])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_aspnet_Profile] ([UserId], [PropertyNames], [PropertyValuesString], [PropertyValuesBinary], [LastUpdatedDate])
        SELECT   [UserId],
                 [PropertyNames],
                 [PropertyValuesString],
                 [PropertyValuesBinary],
                 [LastUpdatedDate]
        FROM     [dbo].[aspnet_Profile]
        ORDER BY [UserId] ASC;
    END

DROP TABLE [dbo].[aspnet_Profile];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_aspnet_Profile]', N'aspnet_Profile';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_aspnet_Profile1]', N'PK_aspnet_Profile', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
EXECUTE sp_tableoption @TableNamePattern = N'[dbo].[aspnet_Profile]', @OptionName = N'text in row', @OptionValue = N'6000';


GO
PRINT N'Starting rebuilding table [dbo].[aspnet_WebEvent_Events]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_aspnet_WebEvent_Events] (
    [EventId]                CHAR (32)       NOT NULL,
    [EventTimeUtc]           DATETIME        NOT NULL,
    [EventTime]              DATETIME        NOT NULL,
    [EventType]              NVARCHAR (256)  NOT NULL,
    [EventSequence]          DECIMAL (19)    NOT NULL,
    [EventOccurrence]        DECIMAL (19)    NOT NULL,
    [EventCode]              INT             NOT NULL,
    [EventDetailCode]        INT             NOT NULL,
    [Message]                NVARCHAR (1024) NULL,
    [ApplicationPath]        NVARCHAR (256)  NULL,
    [ApplicationVirtualPath] NVARCHAR (256)  NULL,
    [MachineName]            NVARCHAR (256)  NOT NULL,
    [RequestUrl]             NVARCHAR (1024) NULL,
    [ExceptionType]          NVARCHAR (256)  NULL,
    [Test]                   INT             NULL,
    [Details]                NTEXT           NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_aspnet_WebEvent_Events1] PRIMARY KEY CLUSTERED ([EventId] ASC) ON [PRIMARY]
) ON [PRIMARY];

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[aspnet_WebEvent_Events])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_aspnet_WebEvent_Events] ([EventId], [EventTimeUtc], [EventTime], [EventType], [EventSequence], [EventOccurrence], [EventCode], [EventDetailCode], [Message], [ApplicationPath], [ApplicationVirtualPath], [MachineName], [RequestUrl], [ExceptionType], [Details])
        SELECT   [EventId],
                 [EventTimeUtc],
                 [EventTime],
                 [EventType],
                 [EventSequence],
                 [EventOccurrence],
                 [EventCode],
                 [EventDetailCode],
                 [Message],
                 [ApplicationPath],
                 [ApplicationVirtualPath],
                 [MachineName],
                 [RequestUrl],
                 [ExceptionType],
                 [Details]
        FROM     [dbo].[aspnet_WebEvent_Events]
        ORDER BY [EventId] ASC;
    END

DROP TABLE [dbo].[aspnet_WebEvent_Events];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_aspnet_WebEvent_Events]', N'aspnet_WebEvent_Events';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_aspnet_WebEvent_Events1]', N'PK_aspnet_WebEvent_Events', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[DataSourceTransformation]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_DataSourceTransformation] (
    [ID]                      UNIQUEIDENTIFIER CONSTRAINT [DF_DataSourceTransformation_ID] DEFAULT (newid()) NOT NULL,
    [TransformationTypeID]    UNIQUEIDENTIFIER NOT NULL,
    [PhenomenonID]            UNIQUEIDENTIFIER NOT NULL,
    [PhenomenonOfferingID]    UNIQUEIDENTIFIER NULL,
    [PhenomenonUOMID]         UNIQUEIDENTIFIER NULL,
    [StartDate]               DATETIME         NULL,
    [EndDate]                 DATETIME         NULL,
    [DataSourceID]            UNIQUEIDENTIFIER NOT NULL,
    [Definition]              TEXT             NOT NULL,
    [ParamA]                  FLOAT (53)       NULL,
    [ParamB]                  FLOAT (53)       NULL,
    [ParamC]                  FLOAT (53)       NULL,
    [ParamD]                  FLOAT (53)       NULL,
    [ParamE]                  FLOAT (53)       NULL,
    [ParamF]                  FLOAT (53)       NULL,
    [ParamG]                  FLOAT (53)       NULL,
    [ParamH]                  FLOAT (53)       NULL,
    [ParamI]                  FLOAT (53)       NULL,
    [ParamJ]                  FLOAT (53)       NULL,
    [ParamK]                  FLOAT (53)       NULL,
    [ParamL]                  FLOAT (53)       NULL,
    [ParamM]                  FLOAT (53)       NULL,
    [ParamN]                  FLOAT (53)       NULL,
    [ParamO]                  FLOAT (53)       NULL,
    [ParamP]                  FLOAT (53)       NULL,
    [ParamQ]                  FLOAT (53)       NULL,
    [ParamR]                  FLOAT (53)       NULL,
    [ParamS]                  FLOAT (53)       NULL,
    [ParamT]                  FLOAT (53)       NULL,
    [ParamU]                  FLOAT (53)       NULL,
    [ParamV]                  FLOAT (53)       NULL,
    [ParamW]                  FLOAT (53)       NULL,
    [ParamX]                  FLOAT (53)       NULL,
    [ParamY]                  FLOAT (53)       NULL,
    [NewPhenomenonID]         UNIQUEIDENTIFIER NULL,
    [NewPhenomenonOfferingID] UNIQUEIDENTIFIER NULL,
    [NewPhenomenonUOMID]      UNIQUEIDENTIFIER NULL,
    [Rank]                    INT              CONSTRAINT [DF_DataSourceTransformation_Rank] DEFAULT ((0)) NULL,
    [SensorID]                UNIQUEIDENTIFIER NULL,
    [UserId]                  UNIQUEIDENTIFIER NULL,
    [AddedAt]                 DATETIME         CONSTRAINT [DF_DataSourceTransformation_AddedAt] DEFAULT (getdate()) NULL,
    [UpdatedAt]               DATETIME         CONSTRAINT [DF_DataSourceTransformation_UpdatedAt] DEFAULT (getdate()) NULL,
    [RowVersion]              ROWVERSION       NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_DataSourceTransformation1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [tmp_ms_xx_constraint_UX_DataSourceTransformation1] UNIQUE NONCLUSTERED ([DataSourceID] ASC, [SensorID] ASC, [Rank] ASC, [TransformationTypeID] ASC, [PhenomenonID] ASC, [PhenomenonOfferingID] ASC, [PhenomenonUOMID] ASC, [NewPhenomenonOfferingID] ASC, [NewPhenomenonUOMID] ASC, [StartDate] ASC, [EndDate] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[DataSourceTransformation])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_DataSourceTransformation] ([ID], [TransformationTypeID], [PhenomenonID], [PhenomenonOfferingID], [PhenomenonUOMID], [StartDate], [EndDate], [DataSourceID], [Definition], [NewPhenomenonOfferingID], [NewPhenomenonUOMID], [Rank], [SensorID], [UserId], [AddedAt], [UpdatedAt], [ParamA], [ParamB], [ParamC], [ParamD], [ParamE], [ParamF], [ParamG], [ParamH], [ParamI], [ParamJ], [ParamK], [ParamL], [ParamM], [ParamN], [ParamO], [ParamP], [ParamQ], [ParamR], [ParamS], [ParamT], [ParamU], [ParamV], [ParamW], [ParamX], [ParamY], [NewPhenomenonID])
        SELECT   [ID],
                 [TransformationTypeID],
                 [PhenomenonID],
                 [PhenomenonOfferingID],
                 [PhenomenonUOMID],
                 [StartDate],
                 [EndDate],
                 [DataSourceID],
                 [Definition],
                 [NewPhenomenonOfferingID],
                 [NewPhenomenonUOMID],
                 [Rank],
                 [SensorID],
                 [UserId],
                 [AddedAt],
                 [UpdatedAt],
                 [ParamA],
                 [ParamB],
                 [ParamC],
                 [ParamD],
                 [ParamE],
                 [ParamF],
                 [ParamG],
                 [ParamH],
                 [ParamI],
                 [ParamJ],
                 [ParamK],
                 [ParamL],
                 [ParamM],
                 [ParamN],
                 [ParamO],
                 [ParamP],
                 [ParamQ],
                 [ParamR],
                 [ParamS],
                 [ParamT],
                 [ParamU],
                 [ParamV],
                 [ParamW],
                 [ParamX],
                 [ParamY],
                 [NewPhenomenonID]
        FROM     [dbo].[DataSourceTransformation]
        ORDER BY [ID] ASC;
    END

DROP TABLE [dbo].[DataSourceTransformation];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_DataSourceTransformation]', N'DataSourceTransformation';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_DataSourceTransformation1]', N'PK_DataSourceTransformation', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_UX_DataSourceTransformation1]', N'UX_DataSourceTransformation', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_DataSourceID]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_DataSourceID]
    ON [dbo].[DataSourceTransformation]([DataSourceID] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_TransformationTypeID]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_TransformationTypeID]
    ON [dbo].[DataSourceTransformation]([TransformationTypeID] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_PhenomenonID]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_PhenomenonID]
    ON [dbo].[DataSourceTransformation]([PhenomenonID] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_PhenomenonOfferingID]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_PhenomenonOfferingID]
    ON [dbo].[DataSourceTransformation]([PhenomenonOfferingID] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_PhenomenonUOMID]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_PhenomenonUOMID]
    ON [dbo].[DataSourceTransformation]([PhenomenonUOMID] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_NewPhenomenonID]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_NewPhenomenonID]
    ON [dbo].[DataSourceTransformation]([NewPhenomenonID] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_NewPhenomenonOfferingID]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_NewPhenomenonOfferingID]
    ON [dbo].[DataSourceTransformation]([NewPhenomenonOfferingID] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_NewPhenomenonUOMID]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_NewPhenomenonUOMID]
    ON [dbo].[DataSourceTransformation]([NewPhenomenonUOMID] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_UserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_UserId]
    ON [dbo].[DataSourceTransformation]([UserId] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_SensorID]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_SensorID]
    ON [dbo].[DataSourceTransformation]([SensorID] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_Rank]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_Rank]
    ON [dbo].[DataSourceTransformation]([DataSourceID] ASC, [Rank] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_StartDate]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_StartDate]
    ON [dbo].[DataSourceTransformation]([DataSourceID] ASC, [StartDate] ASC);


GO
PRINT N'Creating [dbo].[DataSourceTransformation].[IX_DataSourceTransformation_EndDate]...';


GO
CREATE NONCLUSTERED INDEX [IX_DataSourceTransformation_EndDate]
    ON [dbo].[DataSourceTransformation]([DataSourceID] ASC, [EndDate] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[ImportBatch]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_ImportBatch] (
    [ID]             UNIQUEIDENTIFIER CONSTRAINT [DF_ImportBatch_ID] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [Code]           INT              IDENTITY (1, 1) NOT NULL,
    [DataSourceID]   UNIQUEIDENTIFIER NOT NULL,
    [ImportDate]     DATETIME         CONSTRAINT [DF_ImportBatch_ImportDate] DEFAULT (getdate()) NOT NULL,
    [Status]         INT              NOT NULL,
    [UserId]         UNIQUEIDENTIFIER NOT NULL,
    [FileName]       VARCHAR (250)    NULL,
    [LogFileName]    VARCHAR (250)    NULL,
    [Comment]        VARCHAR (8000)   NULL,
    [StatusID]       UNIQUEIDENTIFIER NULL,
    [StatusReasonID] UNIQUEIDENTIFIER NULL,
    [Issues]         VARCHAR (1000)   NULL,
    [DurationInSecs] INT              NULL,
    [AddedAt]        DATETIME         CONSTRAINT [DF_ImportBatch_AddedAt] DEFAULT (getdate()) NULL,
    [UpdatedAt]      DATETIME         CONSTRAINT [DF_ImportBatch_UpdatedAt] DEFAULT (getdate()) NULL,
    [RowVersion]     ROWVERSION       NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_ImportBatch1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [tmp_ms_xx_constraint_UX_ImportBatch_Code1] UNIQUE NONCLUSTERED ([Code] ASC),
    CONSTRAINT [tmp_ms_xx_constraint_UX_ImportBatch1] UNIQUE NONCLUSTERED ([DataSourceID] ASC, [ImportDate] ASC, [LogFileName] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[ImportBatch])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_ImportBatch] ON;
        INSERT INTO [dbo].[tmp_ms_xx_ImportBatch] ([ID], [Code], [DataSourceID], [ImportDate], [Status], [UserId], [FileName], [LogFileName], [Comment], [StatusID], [StatusReasonID], [Issues], [AddedAt], [UpdatedAt], [DurationInSecs])
        SELECT   [ID],
                 [Code],
                 [DataSourceID],
                 [ImportDate],
                 [Status],
                 [UserId],
                 [FileName],
                 [LogFileName],
                 [Comment],
                 [StatusID],
                 [StatusReasonID],
                 [Issues],
                 [AddedAt],
                 [UpdatedAt],
                 [DurationInSecs]
        FROM     [dbo].[ImportBatch]
        ORDER BY [ID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_ImportBatch] OFF;
    END

DROP TABLE [dbo].[ImportBatch];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_ImportBatch]', N'ImportBatch';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_ImportBatch1]', N'PK_ImportBatch', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_UX_ImportBatch_Code1]', N'UX_ImportBatch_Code', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_UX_ImportBatch1]', N'UX_ImportBatch', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[ImportBatch].[IX_ImportBatch_DataSourceID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatch_DataSourceID]
    ON [dbo].[ImportBatch]([DataSourceID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatch].[IX_ImportBatch_UserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatch_UserId]
    ON [dbo].[ImportBatch]([UserId] ASC);


GO
PRINT N'Creating [dbo].[ImportBatch].[IX_ImportBatch_ImportDate]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatch_ImportDate]
    ON [dbo].[ImportBatch]([DataSourceID] ASC, [ImportDate] ASC);


GO
PRINT N'Creating [dbo].[ImportBatch].[IX_ImportBatch_LogFileName]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatch_LogFileName]
    ON [dbo].[ImportBatch]([DataSourceID] ASC, [LogFileName] ASC);


GO
PRINT N'Creating [dbo].[ImportBatch].[IX_ImportBatch_StatusID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatch_StatusID]
    ON [dbo].[ImportBatch]([StatusID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatch].[IX_ImportBatch_StatusReasonID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatch_StatusReasonID]
    ON [dbo].[ImportBatch]([StatusReasonID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatch].[IX_ImportBatch_DurationInSecs]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatch_DurationInSecs]
    ON [dbo].[ImportBatch]([DurationInSecs] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[ImportBatchSummary]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_ImportBatchSummary] (
    [ID]                   UNIQUEIDENTIFIER CONSTRAINT [DF_ImportBatchSummary_ID] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [ImportBatchID]        UNIQUEIDENTIFIER NOT NULL,
    [SensorID]             UNIQUEIDENTIFIER NOT NULL,
    [InstrumentID]         UNIQUEIDENTIFIER NOT NULL,
    [StationID]            UNIQUEIDENTIFIER NOT NULL,
    [SiteID]               UNIQUEIDENTIFIER NOT NULL,
    [PhenomenonOfferingID] UNIQUEIDENTIFIER NOT NULL,
    [PhenomenonUOMID]      UNIQUEIDENTIFIER NOT NULL,
    [Count]                INT              NOT NULL,
    [Minimum]              FLOAT (53)       NULL,
    [Maximum]              FLOAT (53)       NULL,
    [Average]              FLOAT (53)       NULL,
    [StandardDeviation]    FLOAT (53)       NULL,
    [Variance]             FLOAT (53)       NULL,
    [LatitudeNorth]        FLOAT (53)       NULL,
    [LatitudeSouth]        FLOAT (53)       NULL,
    [LongitudeWest]        FLOAT (53)       NULL,
    [LongitudeEast]        FLOAT (53)       NULL,
    [ElevationMinimum]     FLOAT (53)       NULL,
    [ElevationMaximum]     FLOAT (53)       NULL,
    [StartDate]            DATETIME         NULL,
    [EndDate]              DATETIME         NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_ImportBatchSummary1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [tmp_ms_xx_constraint_UX_ImportBatchSummary1] UNIQUE NONCLUSTERED ([ImportBatchID] ASC, [SensorID] ASC, [PhenomenonOfferingID] ASC, [PhenomenonUOMID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[ImportBatchSummary])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_ImportBatchSummary] ([ID], [ImportBatchID], [SensorID], [InstrumentID], [StationID], [SiteID], [PhenomenonOfferingID], [PhenomenonUOMID], [Count], [Minimum], [Maximum], [Average], [StandardDeviation], [Variance], [StartDate], [EndDate], [LatitudeNorth], [LatitudeSouth], [LongitudeWest], [LongitudeEast], [ElevationMinimum], [ElevationMaximum])
        SELECT   [ID],
                 [ImportBatchID],
                 [SensorID],
                 [InstrumentID],
                 [StationID],
                 [SiteID],
                 [PhenomenonOfferingID],
                 [PhenomenonUOMID],
                 [Count],
                 [Minimum],
                 [Maximum],
                 [Average],
                 [StandardDeviation],
                 [Variance],
                 [StartDate],
                 [EndDate],
                 [LatitudeNorth],
                 [LatitudeSouth],
                 [LongitudeWest],
                 [LongitudeEast],
                 [ElevationMinimum],
                 [ElevationMaximum]
        FROM     [dbo].[ImportBatchSummary]
        ORDER BY [ID] ASC;
    END

DROP TABLE [dbo].[ImportBatchSummary];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_ImportBatchSummary]', N'ImportBatchSummary';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_ImportBatchSummary1]', N'PK_ImportBatchSummary', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_UX_ImportBatchSummary1]', N'UX_ImportBatchSummary', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_ImportBatchID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_ImportBatchID]
    ON [dbo].[ImportBatchSummary]([ImportBatchID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_SensorID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_SensorID]
    ON [dbo].[ImportBatchSummary]([SensorID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_InstrumentID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_InstrumentID]
    ON [dbo].[ImportBatchSummary]([InstrumentID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_StationID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_StationID]
    ON [dbo].[ImportBatchSummary]([StationID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_SiteID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_SiteID]
    ON [dbo].[ImportBatchSummary]([SiteID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_PhenomenonOfferingID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_PhenomenonOfferingID]
    ON [dbo].[ImportBatchSummary]([PhenomenonOfferingID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_PhenomenonUOMID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_PhenomenonUOMID]
    ON [dbo].[ImportBatchSummary]([PhenomenonUOMID] ASC);


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_Count]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_Count]
    ON [dbo].[ImportBatchSummary]([Count] ASC);


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_StartDate]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_StartDate]
    ON [dbo].[ImportBatchSummary]([StartDate] ASC);


GO
PRINT N'Creating [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_EndDate]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_EndDate]
    ON [dbo].[ImportBatchSummary]([EndDate] ASC);


GO
PRINT N'Altering [dbo].[Observation]...';


GO
ALTER TABLE [dbo].[Observation] DROP COLUMN [ValueDecade], COLUMN [ValueYear];


GO
ALTER TABLE [dbo].[Observation]
    ADD [ValueYear]   AS (Year([ValueDate])),
        [ValueDecade] AS (Year([ValueDate]) / 10 * 10);


GO
PRINT N'Creating [dbo].[Observation].[IX_Observation_ValueDecade]...';


GO
CREATE NONCLUSTERED INDEX [IX_Observation_ValueDecade]
    ON [dbo].[Observation]([ValueDecade] ASC)
    ON [Observations];


GO
PRINT N'Creating [dbo].[Observation].[IX_Observation_ValueYear]...';


GO
CREATE NONCLUSTERED INDEX [IX_Observation_ValueYear]
    ON [dbo].[Observation]([ValueYear] ASC)
    ON [Observations];


GO
PRINT N'Starting rebuilding table [dbo].[UserDownloads]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_UserDownloads] (
    [ID]                        UNIQUEIDENTIFIER CONSTRAINT [DF_UserDownloads_ID] DEFAULT (newid()) NOT NULL,
    [Name]                      VARCHAR (150)    NOT NULL,
    [Description]               VARCHAR (5000)   NOT NULL,
    [Title]                     VARCHAR (5000)   NOT NULL,
    [Keywords]                  VARCHAR (1000)   NOT NULL,
    [Date]                      DATETIME         NOT NULL,
    [Input]                     VARCHAR (5000)   NOT NULL,
    [RequeryURL]                VARCHAR (5000)   NOT NULL,
    [DigitalObjectIdentifierID] INT              NOT NULL,
    [MetadataJson]              VARCHAR (MAX)    NOT NULL,
    [MetadataURL]               VARCHAR (2000)   NOT NULL,
    [OpenDataPlatformID]        UNIQUEIDENTIFIER NOT NULL,
    [DownloadURL]               VARCHAR (2000)   NOT NULL,
    [ZipFullName]               VARCHAR (2000)   NOT NULL,
    [ZipCheckSum]               VARCHAR (64)     NOT NULL,
    [ZipURL]                    VARCHAR (2000)   NOT NULL,
    [Citation]                  VARCHAR (5000)   NOT NULL,
    [Places]                    VARCHAR (5000)   NULL,
    [LatitudeNorth]             FLOAT (53)       NULL,
    [LatitudeSouth]             FLOAT (53)       NULL,
    [LongitudeWest]             FLOAT (53)       NULL,
    [LongitudeEast]             FLOAT (53)       NULL,
    [ElevationMinimum]          FLOAT (53)       NULL,
    [ElevationMaximum]          FLOAT (53)       NULL,
    [StartDate]                 DATETIME         NULL,
    [EndDate]                   DATETIME         NULL,
    [UserId]                    VARCHAR (128)    NOT NULL,
    [AddedAt]                   DATETIME         CONSTRAINT [DF_UserDownloads_AddedAt] DEFAULT (getdate()) NULL,
    [AddedBy]                   VARCHAR (128)    NOT NULL,
    [UpdatedAt]                 DATETIME         CONSTRAINT [DF_UserDownloads_UpdatedAt] DEFAULT (getdate()) NULL,
    [UpdatedBy]                 VARCHAR (128)    NOT NULL,
    [RowVersion]                ROWVERSION       NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_UserDownloads1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [tmp_ms_xx_constraint_UX_UserDownloads_UserId_Name1] UNIQUE NONCLUSTERED ([UserId] ASC, [Name] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[UserDownloads])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_UserDownloads] ([ID], [UserId], [Name], [Description], [MetadataURL], [DownloadURL], [Citation], [AddedAt], [AddedBy], [UpdatedAt], [UpdatedBy], [Title], [Keywords], [Date], [Input], [RequeryURL], [DigitalObjectIdentifierID], [MetadataJson], [ZipFullName], [ZipCheckSum], [ZipURL], [Places], [LatitudeNorth], [LatitudeSouth], [LongitudeWest], [LongitudeEast], [ElevationMinimum], [ElevationMaximum], [StartDate], [EndDate], [OpenDataPlatformID])
        SELECT   [ID],
                 [UserId],
                 [Name],
                 [Description],
                 [MetadataURL],
                 [DownloadURL],
                 [Citation],
                 [AddedAt],
                 [AddedBy],
                 [UpdatedAt],
                 [UpdatedBy],
                 [Title],
                 [Keywords],
                 [Date],
                 [Input],
                 [RequeryURL],
                 [DigitalObjectIdentifierID],
                 [MetadataJson],
                 [ZipFullName],
                 [ZipCheckSum],
                 [ZipURL],
                 [Places],
                 [LatitudeNorth],
                 [LatitudeSouth],
                 [LongitudeWest],
                 [LongitudeEast],
                 [ElevationMinimum],
                 [ElevationMaximum],
                 [StartDate],
                 [EndDate],
                 [OpenDataPlatformID]
        FROM     [dbo].[UserDownloads]
        ORDER BY [ID] ASC;
    END

DROP TABLE [dbo].[UserDownloads];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_UserDownloads]', N'UserDownloads';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_UserDownloads1]', N'PK_UserDownloads', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_UX_UserDownloads_UserId_Name1]', N'UX_UserDownloads_UserId_Name', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [dbo].[UserDownloads].[IX_UserDownloads_DOI]...';


GO
CREATE NONCLUSTERED INDEX [IX_UserDownloads_DOI]
    ON [dbo].[UserDownloads]([DigitalObjectIdentifierID] ASC);


GO
PRINT N'Creating [dbo].[PK_aspnet_Membership]...';


GO
ALTER TABLE [dbo].[aspnet_Membership]
    ADD CONSTRAINT [PK_aspnet_Membership] PRIMARY KEY NONCLUSTERED ([UserId] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[PK_aspnet_Paths]...';


GO
ALTER TABLE [dbo].[aspnet_Paths]
    ADD CONSTRAINT [PK_aspnet_Paths] PRIMARY KEY NONCLUSTERED ([PathId] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[PK_aspnet_Roles]...';


GO
ALTER TABLE [dbo].[aspnet_Roles]
    ADD CONSTRAINT [PK_aspnet_Roles] PRIMARY KEY NONCLUSTERED ([RoleId] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[PK_aspnet_SchemaVersions]...';


GO
ALTER TABLE [dbo].[aspnet_SchemaVersions]
    ADD CONSTRAINT [PK_aspnet_SchemaVersions] PRIMARY KEY CLUSTERED ([Feature] ASC, [CompatibleSchemaVersion] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[PK_aspnet_UsersInRoles]...';


GO
ALTER TABLE [dbo].[aspnet_UsersInRoles]
    ADD CONSTRAINT [PK_aspnet_UsersInRoles] PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[aspnet_Applications].[aspnet_Applications_Index]...';


GO
CREATE CLUSTERED INDEX [aspnet_Applications_Index]
    ON [dbo].[aspnet_Applications]([LoweredApplicationName] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating [dbo].[PK_aspnet_Applications]...';


GO
ALTER TABLE [dbo].[aspnet_Applications]
    ADD CONSTRAINT [PK_aspnet_Applications] PRIMARY KEY NONCLUSTERED ([ApplicationId] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[UX_aspnet_Applications_ApplicationName]...';


GO
ALTER TABLE [dbo].[aspnet_Applications]
    ADD CONSTRAINT [UX_aspnet_Applications_ApplicationName] UNIQUE NONCLUSTERED ([ApplicationName] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[UX_aspnet_Applications_LoweredApplicationName]...';


GO
ALTER TABLE [dbo].[aspnet_Applications]
    ADD CONSTRAINT [UX_aspnet_Applications_LoweredApplicationName] UNIQUE NONCLUSTERED ([LoweredApplicationName] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[aspnet_Membership].[aspnet_Membership_index]...';


GO
CREATE CLUSTERED INDEX [aspnet_Membership_index]
    ON [dbo].[aspnet_Membership]([ApplicationId] ASC, [LoweredEmail] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating [dbo].[aspnet_Paths].[aspnet_Paths_index]...';


GO
CREATE UNIQUE CLUSTERED INDEX [aspnet_Paths_index]
    ON [dbo].[aspnet_Paths]([ApplicationId] ASC, [LoweredPath] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating [dbo].[aspnet_PersonalizationPerUser].[aspnet_PersonalizationPerUser_index1]...';


GO
CREATE UNIQUE CLUSTERED INDEX [aspnet_PersonalizationPerUser_index1]
    ON [dbo].[aspnet_PersonalizationPerUser]([PathId] ASC, [UserId] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating [dbo].[PK_aspnet_PersonalizationPerUser]...';


GO
ALTER TABLE [dbo].[aspnet_PersonalizationPerUser]
    ADD CONSTRAINT [PK_aspnet_PersonalizationPerUser] PRIMARY KEY NONCLUSTERED ([Id] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[aspnet_PersonalizationPerUser].[aspnet_PersonalizationPerUser_ncindex2]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [aspnet_PersonalizationPerUser_ncindex2]
    ON [dbo].[aspnet_PersonalizationPerUser]([UserId] ASC, [PathId] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating [dbo].[aspnet_Roles].[aspnet_Roles_index1]...';


GO
CREATE UNIQUE CLUSTERED INDEX [aspnet_Roles_index1]
    ON [dbo].[aspnet_Roles]([ApplicationId] ASC, [LoweredRoleName] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating [dbo].[aspnet_Users].[aspnet_Users_Index]...';


GO
CREATE UNIQUE CLUSTERED INDEX [aspnet_Users_Index]
    ON [dbo].[aspnet_Users]([ApplicationId] ASC, [LoweredUserName] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating [dbo].[PK_aspnet_Users]...';


GO
ALTER TABLE [dbo].[aspnet_Users]
    ADD CONSTRAINT [PK_aspnet_Users] PRIMARY KEY NONCLUSTERED ([UserId] ASC) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[aspnet_Users].[aspnet_Users_Index2]...';


GO
CREATE NONCLUSTERED INDEX [aspnet_Users_Index2]
    ON [dbo].[aspnet_Users]([ApplicationId] ASC, [LastActivityDate] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating [dbo].[aspnet_UsersInRoles].[aspnet_UsersInRoles_index]...';


GO
CREATE NONCLUSTERED INDEX [aspnet_UsersInRoles_index]
    ON [dbo].[aspnet_UsersInRoles]([RoleId] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Applications]...';


GO
ALTER TABLE [dbo].[aspnet_Applications]
    ADD DEFAULT (newid()) FOR [ApplicationId];


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Membership]...';


GO
ALTER TABLE [dbo].[aspnet_Membership]
    ADD DEFAULT ((0)) FOR [PasswordFormat];


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Paths]...';


GO
ALTER TABLE [dbo].[aspnet_Paths]
    ADD DEFAULT (newid()) FOR [PathId];


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_PersonalizationPerUser]...';


GO
ALTER TABLE [dbo].[aspnet_PersonalizationPerUser]
    ADD DEFAULT (newid()) FOR [Id];


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Roles]...';


GO
ALTER TABLE [dbo].[aspnet_Roles]
    ADD DEFAULT (newid()) FOR [RoleId];


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Users]...';


GO
ALTER TABLE [dbo].[aspnet_Users]
    ADD DEFAULT (newid()) FOR [UserId];


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Users]...';


GO
ALTER TABLE [dbo].[aspnet_Users]
    ADD DEFAULT (NULL) FOR [MobileAlias];


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Users]...';


GO
ALTER TABLE [dbo].[aspnet_Users]
    ADD DEFAULT ((0)) FOR [IsAnonymous];


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_PersonalizationAllUsers]...';


GO
ALTER TABLE [dbo].[aspnet_PersonalizationAllUsers] WITH NOCHECK
    ADD FOREIGN KEY ([PathId]) REFERENCES [dbo].[aspnet_Paths] ([PathId]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Profile]...';


GO
ALTER TABLE [dbo].[aspnet_Profile] WITH NOCHECK
    ADD FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_DataLog_DataSourceTransformation]...';


GO
ALTER TABLE [dbo].[DataLog] WITH NOCHECK
    ADD CONSTRAINT [FK_DataLog_DataSourceTransformation] FOREIGN KEY ([DataSourceTransformationID]) REFERENCES [dbo].[DataSourceTransformation] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_TransformationType]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_TransformationType] FOREIGN KEY ([TransformationTypeID]) REFERENCES [dbo].[TransformationType] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_Sensor]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_Sensor] FOREIGN KEY ([SensorID]) REFERENCES [dbo].[Sensor] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_NewPhenomenon]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_NewPhenomenon] FOREIGN KEY ([NewPhenomenonID]) REFERENCES [dbo].[Phenomenon] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_DataSource]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_DataSource] FOREIGN KEY ([DataSourceID]) REFERENCES [dbo].[DataSource] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_Phenomenon]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_Phenomenon] FOREIGN KEY ([PhenomenonID]) REFERENCES [dbo].[Phenomenon] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_PhenomenonOffering]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_PhenomenonOffering] FOREIGN KEY ([PhenomenonOfferingID]) REFERENCES [dbo].[PhenomenonOffering] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_NewPhenomenonOffering]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_NewPhenomenonOffering] FOREIGN KEY ([NewPhenomenonOfferingID]) REFERENCES [dbo].[PhenomenonOffering] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_PhenomenonUOM]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_PhenomenonUOM] FOREIGN KEY ([PhenomenonUOMID]) REFERENCES [dbo].[PhenomenonUOM] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_NewPhenomenonUOM]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_NewPhenomenonUOM] FOREIGN KEY ([NewPhenomenonUOMID]) REFERENCES [dbo].[PhenomenonUOM] ([ID]);


GO
PRINT N'Creating [dbo].[FK_DataSourceTransformation_aspnet_Users]...';


GO
ALTER TABLE [dbo].[DataSourceTransformation] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceTransformation_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_DataLog_ImportBatch]...';


GO
ALTER TABLE [dbo].[DataLog] WITH NOCHECK
    ADD CONSTRAINT [FK_DataLog_ImportBatch] FOREIGN KEY ([ImportBatchID]) REFERENCES [dbo].[ImportBatch] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatchSummary_ImportBatchID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_ImportBatchID] FOREIGN KEY ([ImportBatchID]) REFERENCES [dbo].[ImportBatch] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatch_DataSource]...';


GO
ALTER TABLE [dbo].[ImportBatch] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatch_DataSource] FOREIGN KEY ([DataSourceID]) REFERENCES [dbo].[DataSource] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatch_Status]...';


GO
ALTER TABLE [dbo].[ImportBatch] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatch_Status] FOREIGN KEY ([StatusID]) REFERENCES [dbo].[Status] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatch_StatusReason]...';


GO
ALTER TABLE [dbo].[ImportBatch] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatch_StatusReason] FOREIGN KEY ([StatusReasonID]) REFERENCES [dbo].[StatusReason] ([ID]);


GO
PRINT N'Creating [dbo].[FK_Observation_ImportBatch]...';


GO
ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK_Observation_ImportBatch] FOREIGN KEY ([ImportBatchID]) REFERENCES [dbo].[ImportBatch] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatch_aspnet_Users]...';


GO
ALTER TABLE [dbo].[ImportBatch] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatch_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_ImportBatchSummary_SensorID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_SensorID] FOREIGN KEY ([SensorID]) REFERENCES [dbo].[Sensor] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatchSummary_PhenomenonOfferingID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_PhenomenonOfferingID] FOREIGN KEY ([PhenomenonOfferingID]) REFERENCES [dbo].[PhenomenonOffering] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatchSummary_PhenomenonUOMID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_PhenomenonUOMID] FOREIGN KEY ([PhenomenonUOMID]) REFERENCES [dbo].[PhenomenonUOM] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatchSummary_InstrumentID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_InstrumentID] FOREIGN KEY ([InstrumentID]) REFERENCES [dbo].[Instrument] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatchSummary_StationID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_StationID] FOREIGN KEY ([StationID]) REFERENCES [dbo].[Station] ([ID]);


GO
PRINT N'Creating [dbo].[FK_ImportBatchSummary_SiteID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_SiteID] FOREIGN KEY ([SiteID]) REFERENCES [dbo].[Site] ([ID]);


GO
PRINT N'Creating [dbo].[FK_UserDownloads_DigitalObjectIdentifiers]...';


GO
ALTER TABLE [dbo].[UserDownloads] WITH NOCHECK
    ADD CONSTRAINT [FK_UserDownloads_DigitalObjectIdentifiers] FOREIGN KEY ([DigitalObjectIdentifierID]) REFERENCES [dbo].[DigitalObjectIdentifiers] ([ID]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Membership]...';


GO
ALTER TABLE [dbo].[aspnet_Membership] WITH NOCHECK
    ADD FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[aspnet_Applications] ([ApplicationId]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Membership]...';


GO
ALTER TABLE [dbo].[aspnet_Membership] WITH NOCHECK
    ADD FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Paths]...';


GO
ALTER TABLE [dbo].[aspnet_Paths] WITH NOCHECK
    ADD FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[aspnet_Applications] ([ApplicationId]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_PersonalizationPerUser]...';


GO
ALTER TABLE [dbo].[aspnet_PersonalizationPerUser] WITH NOCHECK
    ADD FOREIGN KEY ([PathId]) REFERENCES [dbo].[aspnet_Paths] ([PathId]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_PersonalizationPerUser]...';


GO
ALTER TABLE [dbo].[aspnet_PersonalizationPerUser] WITH NOCHECK
    ADD FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Roles]...';


GO
ALTER TABLE [dbo].[aspnet_Roles] WITH NOCHECK
    ADD FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[aspnet_Applications] ([ApplicationId]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_Users]...';


GO
ALTER TABLE [dbo].[aspnet_Users] WITH NOCHECK
    ADD FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[aspnet_Applications] ([ApplicationId]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_UsersInRoles]...';


GO
ALTER TABLE [dbo].[aspnet_UsersInRoles] WITH NOCHECK
    ADD FOREIGN KEY ([RoleId]) REFERENCES [dbo].[aspnet_Roles] ([RoleId]);


GO
PRINT N'Creating unnamed constraint on [dbo].[aspnet_UsersInRoles]...';


GO
ALTER TABLE [dbo].[aspnet_UsersInRoles] WITH NOCHECK
    ADD FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_AuditLog_aspnet_Users]...';


GO
ALTER TABLE [dbo].[AuditLog] WITH NOCHECK
    ADD CONSTRAINT [FK_AuditLog_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_DataLog_aspnet_Users]...';


GO
ALTER TABLE [dbo].[DataLog] WITH NOCHECK
    ADD CONSTRAINT [FK_DataLog_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_DataSchema_aspnet_Users]...';


GO
ALTER TABLE [dbo].[DataSchema] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSchema_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_DataSource_aspnet_Users]...';


GO
ALTER TABLE [dbo].[DataSource] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSource_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_DataSourceType_aspnet_Users]...';


GO
ALTER TABLE [dbo].[DataSourceType] WITH NOCHECK
    ADD CONSTRAINT [FK_DataSourceType_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Instrument_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Instrument] WITH NOCHECK
    ADD CONSTRAINT [FK_Instrument_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Instrument_Sensor_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Instrument_Sensor] WITH NOCHECK
    ADD CONSTRAINT [FK_Instrument_Sensor_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Observation_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK_Observation_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Offering_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Offering] WITH NOCHECK
    ADD CONSTRAINT [FK_Offering_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Organisation_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Organisation] WITH NOCHECK
    ADD CONSTRAINT [FK_Organisation_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Organisation_Instrument_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Organisation_Instrument] WITH NOCHECK
    ADD CONSTRAINT [FK_Organisation_Instrument_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Organisation_Site_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Organisation_Site] WITH NOCHECK
    ADD CONSTRAINT [FK_Organisation_Site_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Organisation_Station_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Organisation_Station] WITH NOCHECK
    ADD CONSTRAINT [FK_Organisation_Station_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_OrganisationRole_aspnet_Users]...';


GO
ALTER TABLE [dbo].[OrganisationRole] WITH NOCHECK
    ADD CONSTRAINT [FK_OrganisationRole_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Phenomenon_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Phenomenon] WITH NOCHECK
    ADD CONSTRAINT [FK_Phenomenon_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_PhenomenonOffering_aspnet_Users]...';


GO
ALTER TABLE [dbo].[PhenomenonOffering] WITH NOCHECK
    ADD CONSTRAINT [FK_PhenomenonOffering_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_PhenomenonUOM_aspnet_Users]...';


GO
ALTER TABLE [dbo].[PhenomenonUOM] WITH NOCHECK
    ADD CONSTRAINT [FK_PhenomenonUOM_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Programme_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Programme] WITH NOCHECK
    ADD CONSTRAINT [FK_Programme_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Project_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Project] WITH NOCHECK
    ADD CONSTRAINT [FK_Project_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Project_Station_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Project_Station] WITH NOCHECK
    ADD CONSTRAINT [FK_Project_Station_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_RoleModule_aspnet_Roles]...';


GO
ALTER TABLE [dbo].[RoleModule] WITH NOCHECK
    ADD CONSTRAINT [FK_RoleModule_aspnet_Roles] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[aspnet_Roles] ([RoleId]);


GO
PRINT N'Creating [dbo].[FK_SchemaColumn_aspnet_Users]...';


GO
ALTER TABLE [dbo].[SchemaColumn] WITH NOCHECK
    ADD CONSTRAINT [FK_SchemaColumn_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_SchemaColumnType_aspnet_Users]...';


GO
ALTER TABLE [dbo].[SchemaColumnType] WITH NOCHECK
    ADD CONSTRAINT [FK_SchemaColumnType_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Sensor_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Sensor] WITH NOCHECK
    ADD CONSTRAINT [FK_Sensor_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Site_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Site] WITH NOCHECK
    ADD CONSTRAINT [FK_Site_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Station_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Station] WITH NOCHECK
    ADD CONSTRAINT [FK_Station_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Station_Instrument_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Station_Instrument] WITH NOCHECK
    ADD CONSTRAINT [FK_Station_Instrument_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_Status_aspnet_Users]...';


GO
ALTER TABLE [dbo].[Status] WITH NOCHECK
    ADD CONSTRAINT [FK_Status_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_StatusReason_aspnet_Users]...';


GO
ALTER TABLE [dbo].[StatusReason] WITH NOCHECK
    ADD CONSTRAINT [FK_StatusReason_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_TransformationType_aspnet_Users]...';


GO
ALTER TABLE [dbo].[TransformationType] WITH NOCHECK
    ADD CONSTRAINT [FK_TransformationType_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_UnitOfMeasure_aspnet_Users]...';


GO
ALTER TABLE [dbo].[UnitOfMeasure] WITH NOCHECK
    ADD CONSTRAINT [FK_UnitOfMeasure_aspnet_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
PRINT N'Creating [dbo].[TR_DataSourceTransformation_Insert]...';


GO
CREATE TRIGGER [dbo].[TR_DataSourceTransformation_Insert] ON [dbo].[DataSourceTransformation]
FOR INSERT
AS
BEGIN
    SET NoCount ON
    Update
        src
    set
        AddedAt = GetDate(),
        UpdatedAt = NULL
    from
        DataSourceTransformation src
        inner join inserted ins
            on (ins.ID = src.ID)
END
GO
PRINT N'Creating [dbo].[TR_DataSourceTransformation_Update]...';


GO
CREATE TRIGGER [dbo].[TR_DataSourceTransformation_Update] ON [dbo].[DataSourceTransformation]
FOR UPDATE
AS
BEGIN
    SET NoCount ON
    Update
        src
    set
        AddedAt = Coalesce(del.AddedAt, ins.AddedAt, GetDate()),
        UpdatedAt = GETDATE()
    from
        DataSourceTransformation src
        inner join inserted ins
            on (ins.ID = src.ID)
        inner join deleted del
            on (del.ID = src.ID)
END
GO
PRINT N'Creating [dbo].[TR_ImportBatch_Insert]...';


GO
CREATE TRIGGER [dbo].[TR_ImportBatch_Insert] ON [dbo].[ImportBatch]
FOR INSERT
AS
BEGIN
    SET NoCount ON
    Update
        src
    set
        AddedAt = GetDate(),
        UpdatedAt = NULL
    from
        ImportBatch src
        inner join inserted ins
            on (ins.ID = src.ID)
END
GO
PRINT N'Creating [dbo].[TR_ImportBatch_Update]...';


GO
CREATE TRIGGER [dbo].[TR_ImportBatch_Update] ON [dbo].[ImportBatch]
FOR UPDATE
AS
BEGIN
    SET NoCount ON
    Update
        src
    set
        AddedAt = Coalesce(del.AddedAt, ins.AddedAt, GetDate()),
        UpdatedAt = GETDATE()
    from
        ImportBatch src
        inner join inserted ins
            on (ins.ID = src.ID)
        inner join deleted del
            on (del.ID = src.ID)
END
GO
PRINT N'Creating [dbo].[TR_UserDownloads_Insert]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TRIGGER [dbo].[TR_UserDownloads_Insert] ON [dbo].[UserDownloads]
FOR INSERT
AS
BEGIN
  SET NoCount ON
  Update
      src
  set
      AddedAt = GetDate(),
      UpdatedAt = NULL
  from
    UserDownloads src
    inner join inserted ins
      on (ins.ID = src.ID)
END
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [dbo].[TR_UserDownloads_Update]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TRIGGER [dbo].[TR_UserDownloads_Update] ON [dbo].[UserDownloads]
FOR UPDATE
AS
BEGIN
  SET NoCount ON
  Update
      src
  set
    AddedAt = Coalesce(del.AddedAt, ins.AddedAt, GetDate()),
    UpdatedAt = GetDate()
  from
    UserDownloads src
    inner join inserted ins
      on (ins.ID = src.ID)
    inner join deleted del
      on (del.ID = src.ID)
END
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vDataLog]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vDataLog]';


GO
PRINT N'Refreshing [dbo].[vDataSourceTransformation]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vDataSourceTransformation]';


GO
PRINT N'Refreshing [dbo].[vImportBatch]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vImportBatch]';


GO
PRINT N'Refreshing [dbo].[vObservationExpansion]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vObservationExpansion]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vObservation]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vObservation]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vObservationJSON]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vObservationJSON]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vStationObservations]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vStationObservations]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vFeatures]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vFeatures]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vImportBatchSummary]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vImportBatchSummary]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vLocations]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vLocations]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vInventoryDataStreams]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vInventoryDataStreams]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vInventorySensors]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vInventorySensors]';


GO
PRINT N'Refreshing [dbo].[vStationDataStreams]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vStationDataStreams]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vSensorThingsAPIDatastreams]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vSensorThingsAPIDatastreams]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vSensorThingsAPILocations]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vSensorThingsAPILocations]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vSensorThingsAPIObservedProperties]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vSensorThingsAPIObservedProperties]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vSensorThingsAPISensors]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vSensorThingsAPISensors]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vSensorThingsAPIThings]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vSensorThingsAPIThings]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vSensorThingsAPIFeaturesOfInterest]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vSensorThingsAPIFeaturesOfInterest]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vSensorThingsAPIHistoricalLocations]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vSensorThingsAPIHistoricalLocations]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vSensorThingsAPIObservations]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vSensorThingsAPIObservations]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[vUserDownloads]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vUserDownloads]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_PersonalizationAdministration_DeleteAllState]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_PersonalizationAdministration_DeleteAllState]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_PersonalizationAdministration_FindState]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_PersonalizationAdministration_FindState]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_PersonalizationAdministration_GetCountOfState]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_PersonalizationAdministration_GetCountOfState]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_PersonalizationAdministration_ResetSharedState]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_PersonalizationAdministration_ResetSharedState]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_PersonalizationAllUsers_GetPageSettings]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_PersonalizationAllUsers_GetPageSettings]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_PersonalizationAllUsers_ResetPageSettings]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_PersonalizationAllUsers_ResetPageSettings]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_PersonalizationAllUsers_SetPageSettings]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_PersonalizationAllUsers_SetPageSettings]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_AnyDataInTables]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_AnyDataInTables]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_Profile_DeleteInactiveProfiles]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_Profile_DeleteInactiveProfiles]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_Profile_GetNumberOfInactiveProfiles]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_Profile_GetNumberOfInactiveProfiles]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_Profile_GetProfiles]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_Profile_GetProfiles]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_Profile_GetProperties]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_Profile_GetProperties]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_Profile_SetProperties]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_Profile_SetProperties]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_Users_DeleteUser]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_Users_DeleteUser]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_Profile_DeleteProfiles]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_Profile_DeleteProfiles]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [dbo].[aspnet_WebEvent_LogEvent]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[aspnet_WebEvent_LogEvent]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[DataLog] WITH CHECK CHECK CONSTRAINT [FK_DataLog_DataSourceTransformation];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_TransformationType];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_Sensor];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_NewPhenomenon];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_DataSource];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_Phenomenon];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_PhenomenonOffering];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_NewPhenomenonOffering];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_PhenomenonUOM];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_NewPhenomenonUOM];

ALTER TABLE [dbo].[DataSourceTransformation] WITH CHECK CHECK CONSTRAINT [FK_DataSourceTransformation_aspnet_Users];

ALTER TABLE [dbo].[DataLog] WITH CHECK CHECK CONSTRAINT [FK_DataLog_ImportBatch];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_ImportBatchID];

ALTER TABLE [dbo].[ImportBatch] WITH CHECK CHECK CONSTRAINT [FK_ImportBatch_DataSource];

ALTER TABLE [dbo].[ImportBatch] WITH CHECK CHECK CONSTRAINT [FK_ImportBatch_Status];

ALTER TABLE [dbo].[ImportBatch] WITH CHECK CHECK CONSTRAINT [FK_ImportBatch_StatusReason];

ALTER TABLE [dbo].[Observation] WITH CHECK CHECK CONSTRAINT [FK_Observation_ImportBatch];

ALTER TABLE [dbo].[ImportBatch] WITH CHECK CHECK CONSTRAINT [FK_ImportBatch_aspnet_Users];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_SensorID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_PhenomenonOfferingID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_PhenomenonUOMID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_InstrumentID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_StationID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_SiteID];

ALTER TABLE [dbo].[UserDownloads] WITH CHECK CHECK CONSTRAINT [FK_UserDownloads_DigitalObjectIdentifiers];

ALTER TABLE [dbo].[AuditLog] WITH CHECK CHECK CONSTRAINT [FK_AuditLog_aspnet_Users];

ALTER TABLE [dbo].[DataLog] WITH CHECK CHECK CONSTRAINT [FK_DataLog_aspnet_Users];

ALTER TABLE [dbo].[DataSchema] WITH CHECK CHECK CONSTRAINT [FK_DataSchema_aspnet_Users];

ALTER TABLE [dbo].[DataSource] WITH CHECK CHECK CONSTRAINT [FK_DataSource_aspnet_Users];

ALTER TABLE [dbo].[DataSourceType] WITH CHECK CHECK CONSTRAINT [FK_DataSourceType_aspnet_Users];

ALTER TABLE [dbo].[Instrument] WITH CHECK CHECK CONSTRAINT [FK_Instrument_aspnet_Users];

ALTER TABLE [dbo].[Instrument_Sensor] WITH CHECK CHECK CONSTRAINT [FK_Instrument_Sensor_aspnet_Users];

ALTER TABLE [dbo].[Observation] WITH CHECK CHECK CONSTRAINT [FK_Observation_aspnet_Users];

ALTER TABLE [dbo].[Offering] WITH CHECK CHECK CONSTRAINT [FK_Offering_aspnet_Users];

ALTER TABLE [dbo].[Organisation] WITH CHECK CHECK CONSTRAINT [FK_Organisation_aspnet_Users];

ALTER TABLE [dbo].[Organisation_Instrument] WITH CHECK CHECK CONSTRAINT [FK_Organisation_Instrument_aspnet_Users];

ALTER TABLE [dbo].[Organisation_Site] WITH CHECK CHECK CONSTRAINT [FK_Organisation_Site_aspnet_Users];

ALTER TABLE [dbo].[Organisation_Station] WITH CHECK CHECK CONSTRAINT [FK_Organisation_Station_aspnet_Users];

ALTER TABLE [dbo].[OrganisationRole] WITH CHECK CHECK CONSTRAINT [FK_OrganisationRole_aspnet_Users];

ALTER TABLE [dbo].[Phenomenon] WITH CHECK CHECK CONSTRAINT [FK_Phenomenon_aspnet_Users];

ALTER TABLE [dbo].[PhenomenonOffering] WITH CHECK CHECK CONSTRAINT [FK_PhenomenonOffering_aspnet_Users];

ALTER TABLE [dbo].[PhenomenonUOM] WITH CHECK CHECK CONSTRAINT [FK_PhenomenonUOM_aspnet_Users];

ALTER TABLE [dbo].[Programme] WITH CHECK CHECK CONSTRAINT [FK_Programme_aspnet_Users];

ALTER TABLE [dbo].[Project] WITH CHECK CHECK CONSTRAINT [FK_Project_aspnet_Users];

ALTER TABLE [dbo].[Project_Station] WITH CHECK CHECK CONSTRAINT [FK_Project_Station_aspnet_Users];

ALTER TABLE [dbo].[RoleModule] WITH CHECK CHECK CONSTRAINT [FK_RoleModule_aspnet_Roles];

ALTER TABLE [dbo].[SchemaColumn] WITH CHECK CHECK CONSTRAINT [FK_SchemaColumn_aspnet_Users];

ALTER TABLE [dbo].[SchemaColumnType] WITH CHECK CHECK CONSTRAINT [FK_SchemaColumnType_aspnet_Users];

ALTER TABLE [dbo].[Sensor] WITH CHECK CHECK CONSTRAINT [FK_Sensor_aspnet_Users];

ALTER TABLE [dbo].[Site] WITH CHECK CHECK CONSTRAINT [FK_Site_aspnet_Users];

ALTER TABLE [dbo].[Station] WITH CHECK CHECK CONSTRAINT [FK_Station_aspnet_Users];

ALTER TABLE [dbo].[Station_Instrument] WITH CHECK CHECK CONSTRAINT [FK_Station_Instrument_aspnet_Users];

ALTER TABLE [dbo].[Status] WITH CHECK CHECK CONSTRAINT [FK_Status_aspnet_Users];

ALTER TABLE [dbo].[StatusReason] WITH CHECK CHECK CONSTRAINT [FK_StatusReason_aspnet_Users];

ALTER TABLE [dbo].[TransformationType] WITH CHECK CHECK CONSTRAINT [FK_TransformationType_aspnet_Users];

ALTER TABLE [dbo].[UnitOfMeasure] WITH CHECK CHECK CONSTRAINT [FK_UnitOfMeasure_aspnet_Users];


GO
CREATE TABLE [#__checkStatus] (
    id           INT            IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
    [Schema]     NVARCHAR (256),
    [Table]      NVARCHAR (256),
    [Constraint] NVARCHAR (256)
);

SET NOCOUNT ON;

DECLARE tableconstraintnames CURSOR LOCAL FORWARD_ONLY
    FOR SELECT SCHEMA_NAME([schema_id]),
               OBJECT_NAME([parent_object_id]),
               [name],
               0
        FROM   [sys].[objects]
        WHERE  [parent_object_id] IN (OBJECT_ID(N'dbo.aspnet_PersonalizationAllUsers'), OBJECT_ID(N'dbo.aspnet_Profile'), OBJECT_ID(N'dbo.aspnet_Membership'), OBJECT_ID(N'dbo.aspnet_Paths'), OBJECT_ID(N'dbo.aspnet_PersonalizationPerUser'), OBJECT_ID(N'dbo.aspnet_Roles'), OBJECT_ID(N'dbo.aspnet_Users'), OBJECT_ID(N'dbo.aspnet_UsersInRoles'))
               AND [type] IN (N'F', N'C')
                   AND [object_id] IN (SELECT [object_id]
                                       FROM   [sys].[check_constraints]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0
                                       UNION
                                       SELECT [object_id]
                                       FROM   [sys].[foreign_keys]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0);

DECLARE @schemaname AS NVARCHAR (256);

DECLARE @tablename AS NVARCHAR (256);

DECLARE @checkname AS NVARCHAR (256);

DECLARE @is_not_trusted AS INT;

DECLARE @statement AS NVARCHAR (1024);

BEGIN TRY
    OPEN tableconstraintnames;
    FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
    WHILE @@fetch_status = 0
        BEGIN
            PRINT N'Checking constraint: ' + @checkname + N' [' + @schemaname + N'].[' + @tablename + N']';
            SET @statement = N'ALTER TABLE [' + @schemaname + N'].[' + @tablename + N'] WITH ' + CASE @is_not_trusted WHEN 0 THEN N'CHECK' ELSE N'NOCHECK' END + N' CHECK CONSTRAINT [' + @checkname + N']';
            BEGIN TRY
                EXECUTE [sp_executesql] @statement;
            END TRY
            BEGIN CATCH
                INSERT  [#__checkStatus] ([Schema], [Table], [Constraint])
                VALUES                  (@schemaname, @tablename, @checkname);
            END CATCH
            FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
        END
END TRY
BEGIN CATCH
    PRINT ERROR_MESSAGE();
END CATCH

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') >= 0
    CLOSE tableconstraintnames;

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') = -1
    DEALLOCATE tableconstraintnames;

SELECT N'Constraint verification failed:' + [Schema] + N'.' + [Table] + N',' + [Constraint]
FROM   [#__checkStatus];

IF @@ROWCOUNT > 0
    BEGIN
        DROP TABLE [#__checkStatus];
        RAISERROR (N'An error occurred while verifying constraints', 16, 127);
    END

SET NOCOUNT OFF;

DROP TABLE [#__checkStatus];


GO
PRINT N'Update complete.';


GO
