drop view vProjectSiteOld
drop table ProjectSiteOld
drop table Progress
drop procedure progress_Status_Raw
drop view progress_Progress_Resolved
drop view vOfferingPhenomena
drop view vUnitOfMeasurePhenomena