/*
Deployment script for Observations

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Observations"
:setvar DefaultFilePrefix "Observations"
:setvar DefaultDataPath "D:\Program Files\Microsoft SQL Server\MSSQL15.SAEON2019\MSSQL\DATA\"
:setvar DefaultLogPath "D:\Program Files\Microsoft SQL Server\MSSQL15.SAEON2019\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


--GO
--IF EXISTS (SELECT 1
--           FROM   [master].[dbo].[sysdatabases]
--           WHERE  [name] = N'$(DatabaseName)')
--    BEGIN
--        ALTER DATABASE [$(DatabaseName)]
--            SET TEMPORAL_HISTORY_RETENTION ON 
--            WITH ROLLBACK IMMEDIATE;
--    END


GO
PRINT N'Dropping Index [dbo].[Observation].[IX_Observation_ValueDecade]...';


GO
DROP INDEX [IX_Observation_ValueDecade]
    ON [dbo].[Observation];


GO
PRINT N'Dropping Index [dbo].[Observation].[IX_Observation_ValueYear]...';


GO
DROP INDEX [IX_Observation_ValueYear]
    ON [dbo].[Observation];


GO
PRINT N'Altering Table [dbo].[Observation]...';


GO
ALTER TABLE [dbo].[Observation] DROP COLUMN [ValueYear], COLUMN [ValueDecade];


GO
ALTER TABLE [dbo].[Observation]
    ADD [ValueYear]   AS (Year([ValueDate])),
        [ValueDecade] AS (Year([ValueDate]) / 10 * 10);


GO
PRINT N'Creating Index [dbo].[Observation].[IX_Observation_ValueDecade]...';


GO
CREATE NONCLUSTERED INDEX [IX_Observation_ValueDecade]
    ON [dbo].[Observation]([ValueDecade] ASC)
    ON [Observations];


GO
PRINT N'Creating Index [dbo].[Observation].[IX_Observation_ValueYear]...';


GO
CREATE NONCLUSTERED INDEX [IX_Observation_ValueYear]
    ON [dbo].[Observation]([ValueYear] ASC)
    ON [Observations];


GO
PRINT N'Creating Table [dbo].[ImportBatchSummary]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[ImportBatchSummary] (
    [ID]                   UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [ImportBatchID]        UNIQUEIDENTIFIER NOT NULL,
    [SensorID]             UNIQUEIDENTIFIER NOT NULL,
    [InstrumentID]         UNIQUEIDENTIFIER NOT NULL,
    [StationID]            UNIQUEIDENTIFIER NOT NULL,
    [SiteID]               UNIQUEIDENTIFIER NOT NULL,
    [PhenomenonOfferingID] UNIQUEIDENTIFIER NOT NULL,
    [PhenomenonUOMID]      UNIQUEIDENTIFIER NOT NULL,
    [Count]                INT              NOT NULL,
    [ValueCount]           INT              NOT NULL,
    [NullCount]            AS               Count - ValueCount,
    [VerifiedCount]        INT              NOT NULL,
    [UnverifiedCount]      INT              NOT NULL,
    [Minimum]              FLOAT (53)       NULL,
    [Maximum]              FLOAT (53)       NULL,
    [Average]              FLOAT (53)       NULL,
    [StandardDeviation]    FLOAT (53)       NULL,
    [Variance]             FLOAT (53)       NULL,
    [LatitudeNorth]        FLOAT (53)       NULL,
    [LatitudeSouth]        FLOAT (53)       NULL,
    [LongitudeWest]        FLOAT (53)       NULL,
    [LongitudeEast]        FLOAT (53)       NULL,
    [ElevationMinimum]     FLOAT (53)       NULL,
    [ElevationMaximum]     FLOAT (53)       NULL,
    [StartDate]            DATETIME         NULL,
    [EndDate]              DATETIME         NULL,
    CONSTRAINT [PK_ImportBatchSummary] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UX_ImportBatchSummary] UNIQUE NONCLUSTERED ([ImportBatchID] ASC, [SensorID] ASC, [PhenomenonOfferingID] ASC, [PhenomenonUOMID] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_ImportBatchID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_ImportBatchID]
    ON [dbo].[ImportBatchSummary]([ImportBatchID] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_SensorID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_SensorID]
    ON [dbo].[ImportBatchSummary]([SensorID] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_InstrumentID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_InstrumentID]
    ON [dbo].[ImportBatchSummary]([InstrumentID] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_StationID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_StationID]
    ON [dbo].[ImportBatchSummary]([StationID] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_SiteID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_SiteID]
    ON [dbo].[ImportBatchSummary]([SiteID] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_PhenomenonOfferingID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_PhenomenonOfferingID]
    ON [dbo].[ImportBatchSummary]([PhenomenonOfferingID] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_PhenomenonUOMID]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_PhenomenonUOMID]
    ON [dbo].[ImportBatchSummary]([PhenomenonUOMID] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_Count]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_Count]
    ON [dbo].[ImportBatchSummary]([Count] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_ValueCount]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_ValueCount]
    ON [dbo].[ImportBatchSummary]([ValueCount] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_NullCount]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_NullCount]
    ON [dbo].[ImportBatchSummary]([NullCount] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_VerifiedCount]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_VerifiedCount]
    ON [dbo].[ImportBatchSummary]([VerifiedCount] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_UnverifiedCount]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_UnverifiedCount]
    ON [dbo].[ImportBatchSummary]([UnverifiedCount] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_StartDate]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_StartDate]
    ON [dbo].[ImportBatchSummary]([StartDate] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_EndDate]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_EndDate]
    ON [dbo].[ImportBatchSummary]([EndDate] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_LatitudeSouth]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_LatitudeSouth]
    ON [dbo].[ImportBatchSummary]([LatitudeSouth] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_LatitudeNorth]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_LatitudeNorth]
    ON [dbo].[ImportBatchSummary]([LatitudeNorth] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_LongitudeWest]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_LongitudeWest]
    ON [dbo].[ImportBatchSummary]([LongitudeWest] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_LongitudeEast]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_LongitudeEast]
    ON [dbo].[ImportBatchSummary]([LongitudeEast] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_ElevationMinimum]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_ElevationMinimum]
    ON [dbo].[ImportBatchSummary]([ElevationMinimum] ASC);


GO
PRINT N'Creating Index [dbo].[ImportBatchSummary].[IX_ImportBatchSummary_ElevationMaximum]...';


GO
CREATE NONCLUSTERED INDEX [IX_ImportBatchSummary_ElevationMaximum]
    ON [dbo].[ImportBatchSummary]([ElevationMaximum] ASC);


GO
PRINT N'Creating Default Constraint [dbo].[DF_ImportBatchSummary_ID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary]
    ADD CONSTRAINT [DF_ImportBatchSummary_ID] DEFAULT (newid()) FOR [ID];


GO
PRINT N'Creating Foreign Key [dbo].[FK_ImportBatchSummary_ImportBatchID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_ImportBatchID] FOREIGN KEY ([ImportBatchID]) REFERENCES [dbo].[ImportBatch] ([ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ImportBatchSummary_SensorID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_SensorID] FOREIGN KEY ([SensorID]) REFERENCES [dbo].[Sensor] ([ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ImportBatchSummary_InstrumentID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_InstrumentID] FOREIGN KEY ([InstrumentID]) REFERENCES [dbo].[Instrument] ([ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ImportBatchSummary_StationID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_StationID] FOREIGN KEY ([StationID]) REFERENCES [dbo].[Station] ([ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ImportBatchSummary_SiteID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_SiteID] FOREIGN KEY ([SiteID]) REFERENCES [dbo].[Site] ([ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ImportBatchSummary_PhenomenonOfferingID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_PhenomenonOfferingID] FOREIGN KEY ([PhenomenonOfferingID]) REFERENCES [dbo].[PhenomenonOffering] ([ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ImportBatchSummary_PhenomenonUOMID]...';


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH NOCHECK
    ADD CONSTRAINT [FK_ImportBatchSummary_PhenomenonUOMID] FOREIGN KEY ([PhenomenonUOMID]) REFERENCES [dbo].[PhenomenonUOM] ([ID]);


GO
PRINT N'Refreshing View [dbo].[vObservationExpansion]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vObservationExpansion]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing View [dbo].[vSensorThingsAPIObservations]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vSensorThingsAPIObservations]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing View [dbo].[vObservation]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vObservation]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing View [dbo].[vObservationJSON]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vObservationJSON]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing View [dbo].[vStationObservations]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vStationObservations]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating View [dbo].[vImportBatchSummary]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
CREATE VIEW [dbo].[vImportBatchSummary]
AS 
Select distinct
  ImportBatchSummary.*, 
  Phenomenon.ID PhenomenonID, Phenomenon.Code PhenomenonCode, Phenomenon.Name PhenomenonName, Phenomenon.Description PhenomenonDescription, Phenomenon.Url PhenomenonUrl,
  OfferingID OfferingID, Offering.Code OfferingCode, Offering.Name OfferingName, Offering.Description OfferingDescription, 
  UnitOfMeasureID, UnitOfMeasure.Code UnitOfMeasureCode, UnitOfMeasure.Unit UnitOfMeasureUnit, UnitOfMeasure.UnitSymbol UnitOfMeasureSymbol,
  Sensor.Code SensorCode, Sensor.Name SensorName, Sensor.Description SensorDescription,  Sensor.Url SensorUrl,
  Instrument.Code InstrumentCode, Instrument.Name InstrumentName, Instrument.Description InstrumentDescription, Instrument.Url InstrumentUrl,
  Station.Code StationCode, Station.Name StationName, Station.Description StationDescription, Station.Url StationUrl,
  Site.Code SiteCode, Site.Name SiteName, Site.Description SiteDescription, Site.Url SiteUrl,
  Project.ID ProjectID, Project.Code ProjectCode, Project.Name ProjectName, Project.Description ProjectDescription, Project.Url ProjectUrl,
  Programme.ID ProgrammeID, Programme.Code ProgrammeCode, Programme.Name ProgrammeName, Programme.Description ProgrammeDescription, Programme.Url ProgrammeUrl,
  Organisation.ID OrganisationID, Organisation.Code OrganisationCode, Organisation.Name OrganisationName, Organisation.Description OrganisationDescription, Organisation.Url OrganisationUrl
From
  ImportBatchSummary
  inner join Sensor
    on (ImportBatchSummary.SensorID = Sensor.ID)
  inner join Instrument
    on (ImportBatchSummary.InstrumentID = Instrument.ID)
  inner join Station
    on (ImportBatchSummary.StationID = Station.ID)
  inner join Site
    on (ImportBatchSummary.SiteID = Site.ID)
  inner join PhenomenonOffering
    on (ImportBatchSummary.PhenomenonOfferingID = PhenomenonOffering.ID)
  inner join Phenomenon
    on (PhenomenonOffering.PhenomenonID = Phenomenon.ID)
  inner join Offering
    on (PhenomenonOffering.OfferingID = Offering.ID)
  inner join PhenomenonUOM
    on (ImportBatchSummary.PhenomenonUOMID = PhenomenonUOM.ID)
  inner join UnitOfMeasure
    on (PhenomenonUOM.UnitOfMeasureID = UnitOfMeasure.ID)
  left join Project_Station
    on (Project_Station.StationID = Station.ID)
  left join Project
    on (Project_Station.ProjectID = Project.ID)
  left join Programme
    on (Project.ProgrammeID = Programme.ID)
  left join vStationOrganisation
    on (vStationOrganisation.StationID = Station.ID)
  left join Organisation
    on (vStationOrganisation.OrganisationID = Organisation.ID)
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Altering View [dbo].[vInventoryDatasets]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
ALTER VIEW [dbo].[vInventoryDatasets]
AS 
Select
  Row_Number() over (order by StationCode, PhenomenonCode, OfferingCode, UnitOfMeasureCode) ID, s.*
from
(
Select
  OrganisationID, OrganisationCode, OrganisationName, OrganisationDescription, OrganisationUrl,
  ProgrammeID, ProgrammeCode, ProgrammeName, ProgrammeDescription, ProgrammeUrl,
  ProjectID, ProjectCode, ProjectName, ProjectDescription, ProjectUrl,
  SiteID, SiteCode, SiteName, SiteDescription, SiteUrl,
  StationID, StationCode, StationName, StationDescription, StationUrl,
  PhenomenonID, PhenomenonCode, PhenomenonName, PhenomenonDescription, PhenomenonUrl,
  PhenomenonOfferingID, OfferingID, OfferingCode, OfferingName, OfferingDescription,
  PhenomenonUOMID, UnitOfMeasureID, UnitOfMeasureCode, UnitOfMeasureUnit, UnitOfMeasureSymbol,
  Sum(Count) Count,
  Sum(ValueCount) ValueCount,
  Sum(NullCount) NullCount,
  Sum(VerifiedCount) VerifiedCount,
  Sum(UnverifiedCount) UnverifiedCount,
  Min(StartDate) StartDate,
  Max(EndDate) EndDate,
  Max(LatitudeNorth) LatitudeNorth,
  Min(LatitudeSouth) LatitudeSouth,
  Min(LongitudeWest) LongitudeWest,
  Max(LongitudeEast) LongitudeEast,
  Min(ElevationMinimum) ElevationMinimum,
  Max(ElevationMaximum) ElevationMaximum
from
  vImportBatchSummary
group by
  OrganisationID, OrganisationCode, OrganisationName, OrganisationDescription, OrganisationUrl,
  ProgrammeID, ProgrammeCode, ProgrammeName, ProgrammeDescription, ProgrammeUrl,
  ProjectID, ProjectCode, ProjectName, ProjectDescription, ProjectUrl,
  SiteID, SiteCode, SiteName, SiteDescription, SiteUrl,
  StationID, StationCode, StationName, StationDescription, StationUrl,
  PhenomenonID, PhenomenonCode, PhenomenonName, PhenomenonDescription, PhenomenonUrl,
  PhenomenonOfferingID, OfferingID, OfferingCode, OfferingName, OfferingDescription,
  PhenomenonUOMID, UnitOfMeasureID, UnitOfMeasureCode, UnitOfMeasureUnit, UnitOfMeasureSymbol
) s
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing View [dbo].[vLocations]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vLocations]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing View [dbo].[vVariables]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vVariables]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing View [dbo].[vHomeDashboard]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vHomeDashboard]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_ImportBatchID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_SensorID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_InstrumentID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_StationID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_SiteID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_PhenomenonOfferingID];

ALTER TABLE [dbo].[ImportBatchSummary] WITH CHECK CHECK CONSTRAINT [FK_ImportBatchSummary_PhenomenonUOMID];


GO
PRINT N'Update complete.';


GO
